version: '3.5'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules
    stdin_open: true
    tty: true
    networks: 
      - coph-is

networks: 
  coph-is: 
    external: true
