CREATE TABLE company_types (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name varchar(255) UNIQUE NOT NULL,
    description text
);

INSERT INTO company_types (type_name, description) VALUES ('Подрядная компания', 'Описание подрядной компании!');


CREATE TABLE companies (
     id varchar(40) PRIMARY KEY NOT NULL,
     name varchar(255) NOT NULL,
     phone varchar(20),
     email varchar(255),
     home_url varchar(255),
     type_id int references company_types(id),
     inn varchar(20),
     kpp varchar(20),
     ogrn varchar(20),
     address varchar(255),
     full_name varchar(255),
     description text,
     created_at TIMESTAMP NOT NULL
);

