CREATE TABLE IF NOT EXISTS user_credential (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name varchar(255) NOT NULL,
     email varchar(255) UNIQUE NOT NULL,
     password varchar(255) NOT NULL
);