version: '3'
services:

  db-script-service:
    image: postgres:12
    container_name: db-script-service
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: script-service
    
  config-server:
    container_name: config-server
    image: fizmatximik/config-server:1.0.0
    ports:
       - "8071:8071"
    environment:
      ENCRYPT_KEY: "${ENCRYPT_KEY}"