version: '3.5'
services:
  db-script-service:
    image: postgres:12
    container_name: db-script-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: script_service
    volumes:
      - ./postgres-db-script:/var/lib/postgresql/data
    networks: 
      - coph-is
      
  db-data-service:
    image: postgres:12
    container_name: db-data-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: data_service
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data
    networks: 
      - coph-is

  # db-identity-service:
  #   image: postgres:12
  #   container_name: db-identity-service
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: identity_service
  #   volumes:
  #     - ./postgres-db-identity:/var/lib/postgresql/data
  #   # ports:
  #   #   - "5432:5432"
  #   networks: 
  #     - coph-is

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
    ports:
        - "8091:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks: 
      - coph-is

  config-server:
    container_name: config-server
    image: fizmatximik/config-server:1.0.0
    ports:
      - "8071:8071"
    env_file:
      - .env
    networks: 
      - coph-is

networks: 
  coph-is: 
    ipam:
      driver: default
    external: false
    name: coph-is