version: '3'
services:
  script-service:
    container_name: script-service
    image: fizmatximik/script-service:1.0.0 
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_HOST: "192.168.1.70"
      CONFIGSERVER_PORT: "8071"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    ports:
      - "8001:8001"
