version: '3'
services:
  script-service:
    container_name: script-service
    image: fizmatximik/script-service:1.0.0 
    environment:
      SPRING_PROFILES_ACTIVE: dev

      CONFIGSERVER_HOST: "config-server"
      CONFIGSERVER_PORT: "8071"
      ENCRYPT_KEY: ${ENC_KEY}
    ports:
      - "8001:8001"
    networks: 
      - backend
  
  data-service:
    container_name: data-service
    image: fizmatximik/data-service:1.0.0 
    environment:
      SPRING_PROFILES_ACTIVE: dev

      CONFIGSERVER_HOST: "config-server"
      CONFIGSERVER_PORT: "8071"
      ENCRYPT_KEY: ${ENC_KEY}
    ports:
      - "8002:8002"
    networks: 
      - backend

networks: 
  backend: 
    external: 
      name: coph-is

