version: '3'
services:
  db-script-service:
    image: postgres:12
    container_name: db-script-service
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: script-service