version: '3'
services:
  script-service:
    container_name: script-service
    image: fizmatximik/script-service:1.0.0 
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      DATASOURCE_HOST: "192.168.1.70"
      DATASOURCE_PORT: "5444"
      DATASOURCE_DB: "script-service"
    ports:
      - "8001:8001"
