version: '3.5'
services:
  script-service:
    container_name: script-service
    image: fizmatximik/script-service:1.0.0 
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIGSERVER_HOST: "config-server"
      CONFIGSERVER_PORT: "8071"
    ports:
      - "8001:8001"
    networks: 
      - coph-is
    volumes:
      - /home/aleksandr/CoPH-IS/parser:/parser
  
  data-service:
    container_name: data-service
    image: fizmatximik/data-service:1.0.0 
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev

      CONFIGSERVER_HOST: "config-server"
      CONFIGSERVER_PORT: "8071"
    ports:
      - "8002:8002"
    networks: 
      - coph-is

  execute-service:
    container_name: execute-service
    image: fizmatximik/execute-service:1.0.0 
    ports:
      - "8003:8003"
    networks: 
      - coph-is
  

networks: 
  coph-is: 
    external: true

