version: '3.5'
services:
  db-script-service:
    image: postgres:12
    container_name: db-script-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: script-service
    volumes:
      - db-script:/var/lib/postgresql/data
    networks: 
      - coph-is
      
  db-data-service:
    image: postgres:12
    container_name: db-data-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: data-service
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: 
      - coph-is

  config-server:
    container_name: config-server
    image: fizmatximik/config-server:1.0.0
    ports:
      - "8071:8071"
    env_file:
      - .env
    networks: 
      - coph-is

networks: 
  coph-is: 
    ipam:
      driver: default
    external: false
    name: coph-is

volumes:
  db-script:
    driver: local
  db-data:
    driver: local
