spring:
  application:
    name: config-server
  profiles:
    active: git

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/FizMatXimik/config
server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"